tap 'homebrew/bundle'
tap 'homebrew/cask'
tap 'homebrew/core'
tap 'homebrew/services'

brew 'rbenv'
brew 'ruby-build'
brew 'git'
brew 'gh'
brew 'markdownlint-cli2'
brew 'nvm'
brew 'vim'
brew 'rbenv'
brew 'ruby-build'
